# Generated by Django 3.2.7 on 2021-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist_stocks_current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('open', models.FloatField()),
                ('PE_ratio', models.FloatField()),
                ('Mktcap', models.IntegerField()),
                ('Avg_vol', models.IntegerField()),
                ('Yield', models.FloatField()),
                ('Beta', models.FloatField()),
                ('EPS', models.FloatField()),
                ('current_price', models.FloatField()),
            ],
        ),
    ]
