# Generated by Django 3.2.7 on 2021-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockassist', '0002_watchlist_stocks_current_user_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist_stocks_current',
            old_name='Beta',
            new_name='prev_price',
        ),
        migrations.AlterField(
            model_name='watchlist_stocks_current',
            name='Avg_vol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watchlist_stocks_current',
            name='EPS',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlist_stocks_current',
            name='Mktcap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watchlist_stocks_current',
            name='PE_ratio',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlist_stocks_current',
            name='Yield',
            field=models.FloatField(default=-100),
        ),
        migrations.AlterField(
            model_name='watchlist_stocks_current',
            name='company',
            field=models.CharField(default='NULL_STOCK', max_length=200),
        ),
        migrations.AlterField(
            model_name='watchlist_stocks_current',
            name='stock_symbol',
            field=models.CharField(default='NULL_STOCK', max_length=50),
        ),
    ]
