# Generated by Django 3.2.7 on 2021-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockassist', '0003_auto_20210911_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist_stocks_current',
            name='beta',
            field=models.FloatField(default=-1.0),
        ),
    ]
