# Generated by Django 3.2.7 on 2021-09-17 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockassist', '0004_watchlist_stocks_current_beta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='Avg_vol',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='EPS',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='Mktcap',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='PE_ratio',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='Yield',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='company',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='open',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='prev_price',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='stock_symbol',
        ),
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='user_link',
        ),
        migrations.AddField(
            model_name='watchlist_stocks_current',
            name='stk_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist_stocks_current',
            name='stk_name',
            field=models.CharField(default='NULL_FIELD', max_length=200),
        ),
        migrations.AddField(
            model_name='watchlist_stocks_current',
            name='stk_symbol',
            field=models.CharField(default='NULL_FIELD', max_length=50),
        ),
        migrations.AddField(
            model_name='watchlist_stocks_current',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
