# Generated by Django 3.2.7 on 2021-09-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockassist', '0005_auto_20210917_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist_stocks_current',
            old_name='user',
            new_name='watchlist_user',
        ),
    ]
