# Generated by Django 3.2.7 on 2021-09-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockassist', '0007_auto_20210917_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist_stocks_current',
            name='stk_id',
        ),
    ]
