# Generated by Django 3.2.7 on 2021-10-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockassist', '0008_remove_watchlist_stocks_current_stk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist_stocks_current',
            name='stk_price',
            field=models.FloatField(default=-1.0),
        ),
    ]
