# This is a basic workflow to help you get started with Actions

name: CI/CD pipeline

# Controls when the workflow will run
on:
    workflow_dispatch:

env:
  IBM_CLOUD_REGION: eu-gb
  IBM_CLOUD_GROUP: Default
  IBM_CLOUD_SPACE: dev
  IBM_CLOUD_ORG: dev.pvatsa@gmail.com
  MANIFEST_NAME: manifest.yml
  IBM_CLOUD_API: ${{secrets.IBM_API_KEY}}
  DJANGO_SECRET: ${{secrets.DJANGO_SECRET_KEY}}
  IBM_CLOUDANT_API: ${{secrets.IBM_CLOUDANT_API}}
  IBM_CLOUDANT_URL: ${{secrets.IBM_CLOUDANT_URL}}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  IBM-Cf-Build-and-Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Adding relavant env files - 1
        run: cd stockassist && touch .env && cat .env >> CLOUDANT_APIKEY=$IBM_CLOUDANT_API\nCLOUDANT_URL=$IBM_CLOUDNT_URL && cd ..
      
      - name: Adding relavant env files - 2
        run: ls && cd Stock_Assist && touch .env && cat .env >> DJANGO_SECRET_KEY="$DJANGO_SECRET"
    
      - name: Verifing env
        run: cat stockassist/.env && cat Stock_Assist/.env
        
      - name: Initialise IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
        shell: bash

      # Runs a set of commands using the runners shell
      - name: Add CF plugin
        run: ibmcloud cf install -f
        
      - name: Log in
        run: ibmcloud login --apikey "$IBM_CLOUD_API" -r "$IBM_CLOUD_REGION" -g "$IBM_CLOUD_GROUP"
        shell: bash
        
      - name: Target CF
        run: ibmcloud target -r $IBM_CLOUD_REGION -o $IBM_CLOUD_ORG -s $IBM_CLOUD_SPACE -g $IBM_CLOUD_GROUP
        shell: bash
        
      - name: Push App
        run: ibmcloud cf push -f $MANIFEST_NAME
        shell: bash
